addons:
  sonarqube: true
env:
  global:
  - secure: S2lOIdC2ajVpFaES2DumMz0tVN8IxcJyvcZfJwcws3dFR5qw5rFvALAnoOKHfZFkQg2G+t0FaIC+K97PluO5g168v2M+lNtIDV+Ja9EgnjnLjXTvkos5VYCiISB5xZN8tIL6tALLNx0s6CILnwT6DURiuJGNiKklfLPgSFet4eInMQyQhVvL4mO5bJHvciaBhj7CHjljr/yofvPv5bJPsYW3oVCrgtiqZzENrJAzyozuxV+u3R4HFj1ycmeaV55moiXEkjyDbPbYSNT9+kMbucd3g0mESGzNBW/PHy+Os85BDnoogTcMu2zEv/+ewGVlATz59kSb3Ea049BxbkvALSt3hrcDKpRFB3r8WhxS47YOGkKzC3qsROJT+R8bv3ebomg+Jm+jVgPWnVnK+2yMC1J6RA457kY7muZF/JyTqdC5zjOCHJciXcHgD3gkJEra1YgaDI1YbzW8QuttS5ptCj/wIvGaUETiL1HUI52Dok/ziDW9cScLvrSL57DG70O4JXN9xcf6lrgO2LsX6wAn5lrNHzcAuX4XrzAcJFhURqb2dtwyNwSLIbO8Ex1+1dKQIc17xYPe+4HxKsczZVklj298plb0vCsZMEXuC13oNT1ODGtjJAGeSM620nskxkC9g+l5ktz9HduQE1o56ceKySWnyJeqHb1jIhXdmEx4jWs=
  - secure: Aw3robv3od5pKOxpwm0FxGX23k78cnDJCXiBkxdhJrCS6O9N4Ovx0pJ1RkbM783CGht9WDYJbXel8LenIJFSPow7HqyVcUa3Llmgu/Ay8Hj8KNwUTicZFzDkflHSpFt8JnNNf6h0ZvPKjCowp6B2gTDSyPvvvLZOWv5CUkIKy9/GbIZ4uVYVICUmM/p+7G7UFClh1KaMroj/cTFO8nyS7gaybn6u/qWr2oo69bYXdqTklgF+3epEla9gKsmNWgNXt8Ejf7h5exe0vq4urCKkcRUJhDh3ZrkmSYoRZV0nm74PGt8xOLMI3166PVPxRXKInmRSd5v0pFctLbwQG3HwErqgKExth3SRXo72XRTG4nmU5j0Ohm9vIISOWBRTGLGxHMAxvdHHyQEVVoeNbQYQijnU+OjZbqldsnwEOvkrgrcc1RpzalrgCeeeT3PMRaGL4f3qJyLw7vSPPs6rZ2j93XwWTrVmhVzxB+daADodtqlBudHdiy7VKvkftjZ+V2ZQ0ybf9400ZD7WKSCRTVYHXihlh0GMgGHmCGywJnT+YfnBPC7wSJ7+JvBQS3YRMqWTTQ/lQVbZYD/rWXssil4ylwazIXp8Gwjb/p2Jxl7ZBJR2WGWQtYJw32aHXs2KOXORHjkDeWY3Z5/PRczQhQhrOVkTfluU/THGX9Q77DS4v5U=
language: java
script:
- jdk_switcher use openjdk7
- ./gradlew clean
- ./gradlew build
- ./gradlew test
- jdk_switcher use oraclejdk8
- ./gradlew clean
- ./gradlew build
- ./gradlew test
- ./gradlew javadoc
- sonar-scanner -Dsonar.login=$SONAR_HO
after_success:
- .travis/publish-javadoc.sh
- .travis/publish-junitreport.sh
